# ~/.local/share/fcitx5/rime/default.custom.yaml -> rime_wanxiang/default.yaml
# config: https://docs.qq.com/doc/DQ0FqSXBmYVpWVFpy

patch:
  __include: wanxiang_suggested_default:/

  ascii_composer/good_old_caps_lock: true
  ascii_composer/switch_key:
    Caps_Lock: noop
    Control_L: noop
    Control_R: noop
    Shift_L: noop
    Shift_R: clear

  switcher/hotkeys:
    - "F4"
  
  key_binder/bindings:
      - {accept: minus, send: Page_Up, when: has_menu}
      - {accept: equal, send: Page_Down, when: has_menu}
      - {accept: "Control+Shift+3", toggle: ascii_punct, when: always}
      - {accept: "Control+Shift+numbersign", toggle: ascii_punct, when: always}
      - {accept: "Control+Shift+4", toggle: s2t, when: always}
      - {accept: "Control+Shift+dollar", toggle: s2t, when: always}
      - {accept: "Alt+Left", send: "Shift+Left", when: composing}
      - {accept: "Alt+Right", send: "Shift+Right", when: composing}
      - {accept: "Control+w", send: "Control+BackSpace", when: composing}
      - {accept: "Control+e", toggle: chinese_english, when: has_menu}
      - {accept: "Control+a", toggle: tone_hint, when: has_menu}
      - {accept: "Control+s", toggle: tone_display, when: has_menu}
      - {accept: "Control+t", toggle: super_tips, when: has_menu}
      - {accept: "Control+g", toggle: charset_filter, when: has_menu}
      - {accept: "Control+g", toggle: charset_filter, when: composing}
      - {accept: Tab, send: "Control+Right", when: has_menu}
      - {accept: Tab, send: "Control+Right", when: composing}
      - {accept: "Control+Tab", send_sequence: "{Home}{Shift+Right}{1}{Shift+Right}", when: composing}
      - {accept: "/", match: "^/$", send_sequence: "{space}"}