# See https://sw.kovidgoyal.net/kitty/conf.html
include /nix/store/0r6as0l9980vgng8r9b3wngmx7p0q6a0-kitty-themes-0-unstable-2026-07-10/share/kitty-themes/themes/tokyo_night_night.conf

# Shell integration is sourced and configured manually
shell_integration no-rc

cursor_blink_interval 0.500000
cursor_stop_blinking_after 0
font_family FiraCode Nerd Font
font_size 12
hide_window_decorations yes
mouse_hide_wait 3

background_opacity 0.7
background_blur 1
